### PR TITLE
Dependency fix

### LINKED ISSUE #9: Plugin ignores installed vue2-leaflet
Despite having installed the latest version of leaflet, this plugin continues to use an older version instead, overriding whatever version I have installed in my project.

Steps to reproduce:

1. Create a new Vue project using `vue create`.
2. Install latest versions of `leaflet` (1.4.0) and `vue2-leaflet` (2.1.1).
3. Install latest version of `vue2-leaflet-googlemutant`.
4. Run project using `npm run serve`.
5. Open browser console (F12).
6. Type `L`.
7. You will see something like this `{version: "1.3.1", noConflict: ƒ, Control: ƒ, control: ƒ, Browser: {…}, …}` in the console.

As you can see, the global version is `1.3.1`, instead of `1.4.0`. A simple solution to this would be to use `peerDependencies` instead, and let the developers decide which version they want to use.

### PR DESCRIPTION
**Pull request by dnasir**
Should fix #9

### CODE REVIEW

**Comment by thammarith** [comment]
Should fix #11 too (?)

**Comment by dnasir** [comment]
@thammarith Yes

**Comment by pumano** [comment]
@jperelli excuse me sir, maybe you can merge it?

**Comment by jperelli** [comment]
I'll test it manually today before merging

**Comment by pumano** [comment]
@jperelli I test this pull request, it works properly. Previously I created fork for GoogleMutant and make changes to that, but you have old dependencies and your vue2-leaflet-googlemutant have direct binding to old dependencies. That pull request fix both problems: direct binding to old dependencies, and also solve that #11 problem without any changes in google mutant lib

**Comment by daidais** [comment]
Hi, any update about this merge request?

**Comment by jperelli** [comment]
Really sorry about the huge delay guys, I tested it and it works just fine. I'm a little reluctant about breaking dependant apps, so I'll bump the version to 2.0.0 in the next commit, I'l publish the new version to npm in 10 minutes now. Thanks for the support.

**Pull request merged**
